// Правила транслітерації
// 1.00

if(!Translator);
else{

var CyrillicConsonants = "бвгґѓдџђжѕзкќлмнпѱҁѯрстфѳхцчшщ";
Translator.LatinkaToBelarusian = Translator.RuleMap(Array(
Array(CyrillicConsonants,"ja","’я",""),
Array(CyrillicConsonants,"ju","’ю",""),
Array(CyrillicConsonants,"je","’є",""),
Array(CyrillicConsonants,"jo","йо",""),
Array(CyrillicConsonants,"ji","’ї",""),
Array(CyrillicConsonants,"ia","я",""),
Array(CyrillicConsonants,"ie","є",""),
Array(CyrillicConsonants,"io","ьо",""),
Array(CyrillicConsonants,"iu","ю",""),
Array("ì","і"),
Array("á","а́"),
Array("é","е́"),
Array("ý","и́"),
Array("í","і́"),
Array("ó","о́"),
Array("ú","у́"),
Array("a","а"),
Array("ï","і"),
Array("ö","о"),
Array("ü","у"),
Array("ë","е"),
Array("ä","а"),
Array("a","а"),
Array("ﬁ","фі"),
Array("ﬂ","фл"),
Array("b","б"),
Array("v","в"),
Array("h","г"),
Array("g","ґ"),
Array("d","д"),
Array("ď","дь"),
Array("ž","ж"),
Array("z","з"),
Array("ź","зь"),
Array("k","к"),
Array("l","л"),
Array("ľ","ль"),
Array("m","м"),
Array("n","н"),
Array("ń","нь"),
Array("p","п"),
Array("r","р"),
Array("ŕ","рь"),
Array("s","с"),
Array("ś","сь"),
Array("t","т"),
Array("ť","ть"),
Array("f","ф"),
Array("x","x"),
Array("ch","х"),
Array("c","ц"),
Array("ć","ць"),
Array("šč","щ"),
Array("č","ч"),
Array("š","ш"),
Array("ja","я"),
Array("ji","ї"),
Array("je","є"),
Array("ju","ю"),
Array("j","й"),
Array("i","і"),
Array("e","е"),
Array("o","о"),
Array("u","у"),
Array("y","и")
));

Translator.LatinkaToBelarusian.version = "1.00";

}
